### ISSUE TITLE
panics occurring when API is down

### ISSUE THREAD

**Issue by jackmiller334** [linode/linodego#84]
Hi. 

We had some panics using this package coinciding with the recent Linode API service issues. 
https://status.linode.com/incidents/ych41x06fm8k

```
Jun 18 01:10:40 023c8ee9f52b runtime.log: panic: runtime error: invalid memory address or nil pointer dereference
Jun 18 01:10:40 023c8ee9f52b runtime.log: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x865f9a]
Jun 18 01:10:40 023c8ee9f52b runtime.log: goroutine 43 [running]:
Jun 18 01:10:40 023c8ee9f52b runtime.log: github.com/linode/linodego.(*Client).listHelper(0xc000338000, 0xbcb4e0, 0xc000024090, 0xa26300, 0xc00049da40, 0xc00065d660, 0x9e40e0, 0xc000211301)
Jun 18 01:10:40 023c8ee9f52b runtime.log:     /app/src/github.com/linode/linodego/pagination.go:91 +0x5fa
Jun 18 01:10:40 023c8ee9f52b runtime.log: github.com/linode/linodego.(*Client).ListRegions(0xc000338000, 0xbcb4e0, 0xc000024090, 0xc00065d660, 0xc0004dd5a8, 0xfff2a8, 0xc0002c0900, 0x0, 0x0)
Jun 18 01:10:40 023c8ee9f52b runtime.log:     /app/src/github.com/linode/linodego/regions.go:37 +0x78
Jun 18 01:10:40 023c8ee9f52b runtime.log: main.(*LinodeHost).getRegions(0xc0002ac390, 0xc000397500, 0x9, 0x11, 0x0, 0x0)
```

```
Jun 18 00:38:57 023c8ee9f52b runtime.log: panic: runtime error: invalid memory address or nil pointer dereference
Jun 18 00:38:57 023c8ee9f52b runtime.log: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8699f2]
Jun 18 00:38:57 023c8ee9f52b runtime.log: goroutine 101 [running]:
Jun 18 00:38:57 023c8ee9f52b runtime.log: github.com/linode/linodego.(*Client).listHelper(0xc0003b4000, 0xbcb4c0, 0xc000024090, 0xa25b00, 0xc000530f60, 0xc0005611d8, 0x48ae19, 0xc0005610d8)
Jun 18 00:38:57 023c8ee9f52b runtime.log:     /app/src/github.com/linode/linodego/pagination.go:73 +0x4022
Jun 18 00:38:57 023c8ee9f52b runtime.log: github.com/linode/linodego.(*Client).ListImages(0xc0003b4000, 0xbcb4c0, 0xc000024090, 0xc0005611d8, 0x9e0b20, 0xc000074958, 0x182, 0x9e0b20, 0x10001e0)
Jun 18 00:38:57 023c8ee9f52b runtime.log:     /app/src/github.com/linode/linodego/images.go:80 +0x81
```

I believe this to be due to the API outages that occurred.  

A key point to note is that we're using package version **v0.7.1**

Thanks

**Comment by jackmiller334** [comment]
Just a correction, the linodego version that we're using is 0.7.0

**Comment by displague** [comment]
It may have been 0.7.1.. The version wasn't updated in 0.7.1 :disappointed:

**Comment by displague** [comment]
`coupleAPIErrors` is expected to capture any API errors.  It may need to check for some special error cases that only occur during outages.

**Comment by jackmiller334** [comment]
> It may have been 0.7.1.. The version wasn't updated in 0.7.1 😞

Ah. My local changelog is on 0.7.1 but the version string is on 0.7.0. 

Are there any steps to take to help solve this?

**Comment by displague** [comment]
For the version discrepancy - just update to `0.9.0`.

For this problem in general, I think an example of the API response would help to determine why `coupleAPIErrors` was insufficient to handle it.  

Setting the API URL to a localhost port that isn't serving any data, or a localhost port that is running a simple `HTTP/1.0 200\nHello World` web-server may also uncover the problem.

I don't think a Linode API outage would return a 200 response, but if it did, with some HTML response instead of JSON, or perhaps a JSON response that didn't fit the normal API response (no `data` block on a listing endpoint result), that could explain the error.  Run these tests with `LINODE_DEBUG=1` set in the environment.

Create an empty "images" server response:

```bash
cd /tmp
echo "{}" > images # empty string also triggers the error
python -m SimpleHTTPServer
```

Point LinodeGo at it:

```bash
export LINODE_DEBUG=1
export LINODE_URL=http://localhost:8000/
export LINODE_TOKEN=doesnt-need-to-be-real
```

`go run` this file:

```go
package main

import "github.com/linode/linodego"
import "context"

func main() {
        c := linodego.NewClient(nil)

        _, err := c.ListImages(context.Background(), nil)
        if err != nil {
                panic(err)
        }
}
```

Output:
```
2019/06/19 09:32:02 [INFO] LINODE_DEBUG being set to true
RESTY 2019/06/19 09:32:02 
---------------------- REQUEST LOG -----------------------
GET  /images  HTTP/1.1
HOST   : localhost:8000
HEADERS:
                   Accept: application/json
             Content-Type: application/json
               User-Agent: linodego 0.9.0 https://github.com/linode/linodego
BODY   :
***** NO CONTENT *****
----------------------------------------------------------



127.0.0.1 - - [19/Jun/2019 09:32:30] "GET /images HTTP/1.1" 200 -
RESTY 2019/06/19 09:32:30 
---------------------- RESPONSE LOG -----------------------
STATUS          : 200 OK
RECEIVED AT     : 2019-06-19T09:32:30.425963686-04:00
RESPONSE TIME   : 27.580425542s
HEADERS:
           Content-Length: 3
             Content-Type: application/octet-stream
                     Date: Wed, 19 Jun 2019 13:32:30 GMT
            Last-Modified: Wed, 19 Jun 2019 13:29:35 GMT
                   Server: SimpleHTTP/0.6 Python/2.7.16
BODY   :
{}
----------------------------------------------------------
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x758a7c]

goroutine 1 [running]:
github.com/linode/linodego.(*Client).listHelper(0xc00012de18, 0x8e6a00, 0xc0000a6020, 0x7e1d00, 0xc00009d300, 0x0, 0x0, 0x0)
        /home/marques/.local/share/go/src/github.com/linode/linodego/pagination.go:73 +0x38ac
github.com/linode/linodego.(*Client).ListImages(0xc00012de18, 0x8e6a00, 0xc0000a6020, 0x0, 0xc000130510, 0x1, 0xbb8, 0xc0000ac5c0, 0xc0000ac700)
        /home/marques/.local/share/go/src/github.com/linode/linodego/images.go:80 +0x81
main.main()
        /tmp/linodeerr.go:9 +0x92
```

@asauber @jfrederickson @jnschaeffer
